name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements/requirements.txt

      - name: Train Model
        run: python bikeshare_model/train_pipeline.py

      - name: Install dependencies for test
        run: |
          pip install -r requirements/test_requirements.txt

      - name: Test Model
        run: pytest

      - name: Install dependencies for test and build
        run: |
          pip install build
          python -m build
          ls -ltr
 

      - name: Build Package
        run: | 
         ls -ltr dist
         mv dist/*.whl .
         pip install -r bike_sharing_api/requirements.txt

      - name: Fast API
        run: | 
         ls -ltr bike_sharing_api
         python bike_sharing_api/app/main.py &

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'sneh1919'
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: saimadan/bikeshare:latest 
